import Head from "next/head";
import { Inter } from "next/font/google";
import { Box } from "@chakra-ui/react";
import { useRouter } from "next/router";
import Feed from "../components/Feed";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  function createSurvey() {
    router.replace("/start");
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>|
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box onClick={() => createSurvey()}>Create</Box>
        <Feed />
      </main>
    </>
  );
}
